import streamlit as it
import sklearn
import plotly
# -*- coding: utf-8 -*-
"""S3-MC4AI-Gỉai PT Bậc nhất.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11q2EIPJtVWmosMr0C7bdwveQG_MkrY5v
"""

a = float(input("Tham số a: "))
b = float(input("Tham số b: "))

if a == 0:
  if b == 0:
    print("Vô số nghiệm")
  else:
    print("Vô nghiệm")
else:
  print("Phương trình có 1 nghiệm ", -b / a)
